Feat writer progress
AllenNeuralDynamics/voxel pull request #54
Opened 2024-07-24 17:10 UTC by adamkglaser

1. Added share value to allow updating writer progress outside of the main run process
2. Added a shared queue to allow pulling log statements out of the main run process. I have never been able to figure out how to have log statements within a process go to the main logger. This implementation works, but requires calling a ```get_logs()``` function to pull statements out of the Queue.

2024-08-02 15:27 UTC, micahwoodard requested changes

2024-08-02 15:27 UTC, micahwoodard commented on voxel/writers/tiff.py
> +        self.log.info(f"Progress [%]: {self._progress.value*100}")
I'm not sure if I'm missing it, but can there be a DeliminatedProperty of progress that has the unit specificed as %? This is how the view knows to make a progress bar. And can it just return the self._progress.

2024-08-02 17:04 UTC, adamkglaser commented
@micah good catch I forgot, I will update these to use the property.

2024-08-06 18:28 UTC, adamkglaser commented on voxel/writers/tiff.py
> +        self.log.info(f"Progress [%]: {self._progress.value*100}")
@micahwoodard progress is now updated to a deliminated property

2024-08-06 20:15 UTC, merged